### ISSUE TITLE
ToDo - add and remove Issue

### ISSUE THREAD

**Issue by sulaimonaa** [Yonashenok/To-Do-list#4]
Great job creating a beautiful todo app that follows the requirements. However, there is a suggestion based on the project requirement.

#The index of the todo list starts from zero, which means if a user adds 5 todo lists the index of the 5th item will be index 4 which is the opposite of what is required. Could you look into this and make sure it follows the instruction? Great job

**Comment by Yonashenok** [comment]
all done
